#include"header.h"
void CStudent::display()
{
        cout<<rollno<<"\t"<<name<<"\t"<<priority<<endl;
}
CGraph::CGraph(int n)
{
   noOfVertex=n;
   vertices = new CStudent[noOfVertex];
   adjMatrix = new int*[noOfVertex];
   for(int i=0;i<noOfVertex;i++)
      adjMatrix[i]=new int[noOfVertex];
   for(int i=0;i<noOfVertex;i++)
   {
      for(int j=0;j<noOfVertex;j++)
      {
         adjMatrix[i][j]=0;
      }
   }
}
CGraph::~CGraph()
{
        for(int i=0;i<noOfVertex;i++)
           delete[] adjMatrix[i];
        delete[] adjMatrix;
        delete[] vertices;
}
void CGraph::createGraph()
{
   int p,n,source,dest,weight;
   string name;
   for(int i = 0; i < noOfVertex; i++)
   {
      //RollNo. autogenerated
        cout << "Vertex " << i << " Student Details (name): ";
        cin >> name;
        vertices[i] = CStudent(i, name, 999);
   }
   cout<<"Enter the number of edges: ";
   cin>>n;
   for(int i=0;i<n;i++)
   {
      while(1)
      {
        cout<<"Enter source, destination, weight:";
        cin>>source>>dest>>weight;
        if(source>=0 && source<noOfVertex && dest>=0 && dest<noOfVertex)
        {
           adjMatrix[source][dest]=weight;
           adjMatrix[dest][source]=weight;
           break;
        }
        else
           cout<<"Invalid source or destination details\n";
      }
   }
}
void CGraph::displayGraph()
{
   cout<<"Vertex Details\n RollNo\tName\tPriority\n";
   for(int i=0;i<noOfVertex;i++)
   {
      vertices[i].display();
   }
   cout<<"Adjacency Matrix\n";
   cout<<"\t";
   for(int i=0;i<noOfVertex;i++)
   {
      cout<<vertices[i].name<<"\t";
   }
   cout<<endl;
   cout<<"------------------------------------------------\n";
   for(int i=0;i<noOfVertex;i++)
   {
      cout<<vertices[i].name<<"\t|";
      for(int j=0;j<noOfVertex;j++)
      {
         cout<<adjMatrix[i][j]<<"\t";
      }
      cout<<endl;
   }
}
CPQMinHeap::CPQMinHeap(int h)
{
        capacity=pow(2,h+1);
        heap = new CStudent[capacity];
        heapsize=0;
}
CPQMinHeap::~CPQMinHeap()
{
        delete[] heap;
}
int CPQMinHeap::isFull()
{
   if(heapsize==capacity)
      return 1;
   else
      return 0;
}
int CPQMinHeap::isEmpty()
{
   if(heapsize==0)
      return 1;
   else
      return 0;
}
int CPQMinHeap::insert(CStudent s)
{
   if(isFull())
      return 0;
   else
   {
        heap[++heapsize] = s;
        percolateUp(heapsize);
        return 1;
   }
}
void CPQMinHeap::percolateUp(int i)
{
        CStudent temp = heap[i];
        while (i > 1 && heap[i/2].priority > temp.priority)
        {
                heap[i] = heap[i/2];
                i = i/2;
        }
        heap[i] = temp;
}
CStudent CPQMinHeap::returnMin()
{
        if (isEmpty())
           return CStudent();
        else
           return heap[1];
}
int CPQMinHeap::deleteMin()
{
        if (isEmpty())
           return 0;
        else
        {
                heap[1] = heap[heapsize--];
                percolateDown(1);
                return 1;
        }
}
void CPQMinHeap::percolateDown(int i)
{
   int child=2*i;
   CStudent temp=heap[i];
   while(child<heapsize)
   {
      if(child<heapsize && heap[child].priority >heap[child+1].priority)
         child++;
      if(heap[child].priority < temp.priority)
      {
         heap[i]=heap[child];
         i=child;
         child = child*2;
      }
      else
         break;
   }
   heap[i] = temp;
}
void CPQMinHeap::displayHeap()
{
   if(isEmpty())
      cout<<"Heap is empty\n";
   else
   {
      cout<<"RollNo.\tName\tPriority\n";
      for(int i=1;i<=heapsize;i++)
      {
         heap[i].display();
      }
   }
}
void CPQMinHeap::decreaseKeyWith(int r, int newPri)
{
   for(int i=0;i<heapsize;i++)
   {
      if(heap[i].rollno == r)
      {
         heap[i].priority = newPri;
         percolateUp(i);
      }
   }
}
CMST::CMST(CGraph *g)
{
      graph=g;
      noOfVertex = g->noOfVertex;
      vertex = new CStudent[noOfVertex];
      known = new bool[noOfVertex];
      dv = new int[noOfVertex];
      pv = new int[noOfVertex];
      for(int i=0;i<noOfVertex;i++)
      {
         vertex[i] = g->vertices[i];
         known[i]=false;
         dv[i]=INT_MAX;
         pv[i]=-1;
      }
}
CMST::~CMST()
{
   delete[] vertex;
   delete[] known;
   delete[] dv;
   delete[] pv;
}
void CMST::prims(int start)
{
        known[start]=true;
        dv[start]=0;
        vertex[start].priority=0;
        CPQMinHeap pq(noOfVertex);
        pq.insert(vertex[start]);
        while(!pq.isEmpty())
        {
           CStudent u = pq.returnMin();
           cout<<"Dequeued Vertex: \n";
           u.display();
           //if(u.rollno==0)
             // break;
           pq.deleteMin();
           known[u.rollno]=true;
           int j;
           for(int i=0;i<noOfVertex;i++)
           {
              if(graph->adjMatrix[u.rollno][i]!=0 && known[i]!=true)
              {
                 for(j=1;j<=pq.heapsize;j++)
                 {
                    if(pq.heap[j].rollno == vertex[i].rollno)
                       break;
                 }
                 if(j>pq.heapsize)//ith student not in PQ
                 {
                        dv[i] = graph->adjMatrix[u.rollno][i];
                        pv[i] = u.rollno;
                        vertex[i].priority=dv[i];
                        pq.insert(vertex[i]);
                 }
                 else
                 {
                    if(dv[i] > graph->adjMatrix[u.rollno][i])
                    {
                        pq.decreaseKeyWith(vertex[i].rollno, graph->adjMatrix[u.rollno][i]);
                        dv[i] = graph->adjMatrix[u.rollno][i];
                        pv[i] = u.rollno;
                    }
                 }
             }
          }
                        cout<<"Heap Display\n";
                        pq.displayHeap();
              cout<<"Intermediate Tables\n";
              cout<<"Vertex\tKnown\tdv\tpv\n";
              for(int i=0;i<noOfVertex;i++)
              {
                 cout<<vertex[i].name<<"\t"<<known[i]<<"\t"<<dv[i]<<"\t"<<pv[i]<<endl;
              }
        }
        cout<<"MST (Prim's)\nEdge\tWeight\n";
        int totalcost=0;
        for(int i=0;i<noOfVertex;i++)
        {
                if(pv[i]!=-1)
                {
                   cout<<vertex[pv[i]].name <<"-"<<vertex[i].name<<"\t"<<dv[i]<<"\n";
                   totalcost = totalcost + dv[i];
                }
        }
        cout<<"Total MST Cost: "<<totalcost<<endl;
}
